services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27027:27017"
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      #MONGO_INITDB_DATABASE: springdb
    #volumes:
    #  - /mongo-data:/data/mdb
    networks:
      - mongo-app
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/springdb
    networks:
      - mongo-app
    ports:
      - "8080:8080"
networks:
  mongo-app:
volumes:
  mongo-data:
    driver: bridge